name: Run salt tests
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test-salt-linux.yml@c9c3d1193bd64bc2a9def11605608a98a3164d96
    strategy:
      matrix:
        os_version:
          - 7
          - 8
        salt_state:
          - splunkforwarder
        salt_pillar_root:
          - ./tests/pillar/test-linux-main
    with:
      salt-os-version: ${{ matrix.os_version }}
      salt-state: ${{ matrix.salt_state }}
      salt-pillar-root: ${{ matrix.salt_pillar_root }}
